version: '3.8'

services:

  react:
    build:
      context: ./react
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - target: 3000
        published: 80
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      solar:
    depends_on:
      - "flask"
 
  flask:
    build:
      context: ./flask
    ports:
      - target: 8000
        published: 8000
    env_file: .env
    networks:
      solar:
    depends_on:
      - "db"
    
  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - ./seed/01-tables.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./seed/02-owners.sql:/docker-entrypoint-initdb.d/02-owners.sql
      - ./seed/03-projects.sql:/docker-entrypoint-initdb.d/03-projects.sql

    ports:
      - target: 5432
        published: 5432
    networks:
      solar:
        aliases:
          - "solar"

volumes:
  solar-db:

networks:
  solar:
    driver: bridge